name: Valgrind

on: [push]

jobs:
  valgrind:
    strategy:
      matrix:
        distro: [ubuntu-focal, ubuntu-jammy, centos-7, rocky-linux-8, rocky-linux-9, arch-linux]

    runs-on: ubuntu-latest
    env:
      DISTRO: ${{matrix.distro}}
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: |
          pip3 install docker-compose --upgrade
          docker-compose -f test/docker-compose.yml up --build --abort-on-container-exit
